version: '3.8'
services:
  library:
    build: .
    image: library:latest
    ports:
      - 80:8080
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongo_dbdata:/data/db
volumes:
  mongo_dbdata: