logging:
  level:
    root: info
  file:
    name: library.log
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017}
      database: library
    rest:
      base-path: /datarest
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    schema: schema.sql
    data: data.sql
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
library:
  init: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
hystrix.command.bookFindById.execution.isolation.thread.timeoutInMilliseconds: 1000
hystrix.command.bookDeleteById.execution.isolation.thread.timeoutInMilliseconds: 1000
hystrix.command.bookSave.execution.isolation.thread.timeoutInMilliseconds: 1000
hystrix.command.bookFindAll.execution.isolation.thread.timeoutInMilliseconds: 5000
hystrix.command.commentSave.execution.isolation.thread.timeoutInMilliseconds: 1000
hystrix.command.getCommentsByBook.execution.isolation.thread.timeoutInMilliseconds: 1000
hystrix.command.bookDtoToDomainObject.execution.isolation.thread.timeoutInMilliseconds: 1000
hystrix:
  shareSecurityContext: true
