DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID          BIGINT PRIMARY KEY,
                   TITLE       VARCHAR(255));

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID        BIGINT PRIMARY KEY,
                     FULLNAME  VARCHAR(255),
                     DOB       DATE
                     );

DROP TABLE IF EXISTS BOOKS_AUTHORS;
CREATE TABLE BOOKS_AUTHORS(BOOK_ID     BIGINT,
                           AUTHOR_ID   BIGINT);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID         BIGINT PRIMARY KEY,
                    NAME       VARCHAR(255));

DROP TABLE IF EXISTS BOOKS_GENRES;
CREATE TABLE BOOKS_GENRES(BOOK_ID     BIGINT,
                          GENRE_ID    BIGINT);


